Repository fga-eps-mds/2022.1-EuPescador-UserInterface, pull requests merged in 2022-08, with the labels that each got.

#1 Feat/offline services
  app.config.js
  config.ts
  package.json
  src/components/FishLogs/index.tsx
  src/screens/LogsMap/index.tsx
  src/screens/NewFishLog/index.tsx
  src/screens/Register/index.tsx
  src/screens/ViewFishLog/index.tsx
  src/services/adminServices/adminService.ts
  src/services/fishLogService/fishService.ts
  src/services/userServices/userService.ts
  src/services/wikiServices/wikiService.ts
  yarn.lock
Labels: bug, enhancement

#12 Fix: novo tamanho storage
  .eslintrc.json
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/eupescador/app/MainApplication.java
  android/gradle.properties
  package.json
  src/screens/NewFishLog/index.tsx
  src/screens/ViewFishLog/index.tsx
  yarn.lock
Labels: bug, enhancement, HOTFIX, EPS, ANDROID

#13 #5 Adicionando indicativo de carregamento do mapa.
  src/screens/LogsMap/index.tsx
  src/screens/LogsMap/styles.ts
Labels: enhancement, FEATURE, US, EASY, EPS, ANDROID, iOS
